# Keep compiler, runtime library, and validator from one pinned release.
set(WR64_DXC_TOOLCHAIN_DIRECTORY "" CACHE PATH "Optional bin/x64 directory from Microsoft DXC v1.8.2502")

function(wr64_check_dxc_toolchain directory result_variable)
    set(tool_files dxc.exe dxcompiler.dll dxil.dll)
    set(tool_hashes
        ae4bf100b8c64ab03cdc0ee5996d5f212e96c59d6d37340359342d714ac6c004
        f79943b02f73b621421b58a569fd6ee120d0023fb6bfa23844ecad6b00d6a295
        62736e99aa534a942873f92b881a71b2cb6ad62b8d7481ea7a8ad8e9888a8056)
    foreach(index RANGE 0 2)
        list(GET tool_files ${index} tool_file)
        list(GET tool_hashes ${index} expected_hash)
        if(NOT EXISTS "${directory}/${tool_file}")
            set(${result_variable} FALSE PARENT_SCOPE)
            return()
        endif()
        file(SHA256 "${directory}/${tool_file}" actual_hash)
        if(NOT actual_hash STREQUAL expected_hash)
            set(${result_variable} FALSE PARENT_SCOPE)
            return()
        endif()
    endforeach()
    set(${result_variable} TRUE PARENT_SCOPE)
endfunction()

function(wr64_prepare_dxc output_variable)
    # A versioned compiler path also invalidates cached shader build commands.
    set(toolset "${CMAKE_BINARY_DIR}/_deps/wr64-dxc-1.8.2502")
    set(archive_sha256 "70b1913a1bfce4a3e1a5311d16246f4ecdf3a3e613abec8aa529e57668426f85")
    set(download "${CMAKE_BINARY_DIR}/_deps/dxc_2025_02_20.zip")
    if(WR64_DXC_TOOLCHAIN_DIRECTORY)
        wr64_check_dxc_toolchain("${WR64_DXC_TOOLCHAIN_DIRECTORY}" supplied_valid)
        if(NOT supplied_valid)
            message(FATAL_ERROR "WR64_DXC_TOOLCHAIN_DIRECTORY must contain the exact x64 dxc.exe, dxcompiler.dll, and dxil.dll from Microsoft DXC v1.8.2502.")
        endif()
        set(source_bin "${WR64_DXC_TOOLCHAIN_DIRECTORY}")
    else()
        wr64_check_dxc_toolchain("${toolset}" existing_valid)
        if(existing_valid)
            set(${output_variable} "${toolset}" PARENT_SCOPE)
            return()
        endif()
        if(EXISTS "${download}")
            file(SHA256 "${download}" download_hash)
        endif()
        if(NOT download_hash STREQUAL archive_sha256)
            file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/_deps")
            message(STATUS "Acquiring pinned Microsoft DXC v1.8.2502 toolchain")
            file(DOWNLOAD
                "https://github.com/microsoft/DirectXShaderCompiler/releases/download/v1.8.2502/dxc_2025_02_20.zip"
                "${download}" EXPECTED_HASH "SHA256=${archive_sha256}" TLS_VERIFY ON
                TIMEOUT 300 INACTIVITY_TIMEOUT 30 STATUS download_status)
            list(GET download_status 0 download_code)
            if(NOT download_code EQUAL 0)
                message(FATAL_ERROR "DXC toolchain download failed: ${download_status}. Set WR64_DXC_TOOLCHAIN_DIRECTORY for an offline build.")
            endif()
        endif()
        set(extracted "${CMAKE_BINARY_DIR}/_deps/wr64-dxc-1.8.2502-extracted")
        file(ARCHIVE_EXTRACT INPUT "${download}" DESTINATION "${extracted}"
            PATTERNS "bin/x64/dxc.exe" "bin/x64/dxcompiler.dll" "bin/x64/dxil.dll")
        set(source_bin "${extracted}/bin/x64")
        wr64_check_dxc_toolchain("${source_bin}" extracted_valid)
        if(NOT extracted_valid)
            message(FATAL_ERROR "The pinned DXC toolchain has unexpected file hashes.")
        endif()
    endif()
    file(MAKE_DIRECTORY "${toolset}")
    foreach(tool_file dxc.exe dxcompiler.dll dxil.dll)
        configure_file("${source_bin}/${tool_file}" "${toolset}/${tool_file}" COPYONLY)
    endforeach()
    set(${output_variable} "${toolset}" PARENT_SCOPE)
endfunction()
